quan-li-dao-tao/Controllers/AdminController.cs
using PagedList;
using quan_li_dao_tao.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace quan_li_dao_tao.Controllers
{
    public class AdminController : BaseController
    {
        QLSVDbContext _context = null;

        public AdminController()
        {
            _context = new QLSVDbContext();
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddTeacher()
        {
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            return View();
        }

        [HttpPost]
        public ActionResult AddTeacher(teacher teacher)
        {
            if (ModelState.IsValid)
            {
                if (_context.TEACHERs.FirstOrDefault(x => x.teacher_id == teacher.teacher_id) == null)
                {
                    _context.TEACHERs.Add(teacher);
                    if (_context.Users.FirstOrDefault(x => x.user_name == teacher.teacher_id) == null)
                    {
                        var user = new users();
                        user.user_name = teacher.teacher_id;
                        user.pass_word = "1";
                        user.role_id = "teacher";
                        user.status = 1;
                        _context.Users.Add(user);
                    }
                    _context.SaveChanges();
                    ViewBag.ErrorTeacher = "";
                    TempData["AlertMessage"] = "Thêm giảng viên thành công";
                    return RedirectToAction("ManageTeacher");
                }
                else
                {
                    ViewBag.ErrorTeacher = "Mã giảng viên đã tồn tại";
                }
            }
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            return View(teacher);
        }

        public ActionResult ManageTeacher(int? page)
        {
            int pageSize = 5;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listTeacher = _context.TEACHERs.ToList();
            return View(listTeacher.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult SearchTeacher(int? page, string searchTeacher)
        {
            int pageSize = 5;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listTeacher = _context.TEACHERs.Where(x => x.teacher_name.Contains(searchTeacher)).ToList();
            ViewBag.SearchTeacher = searchTeacher;
            return View(listTeacher.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult UpdateTeacher(string id)
        {
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            var res = _context.TEACHERs.FirstOrDefault(x => x.teacher_id == id);
            return View(res);
        }

        [HttpPost]
        public ActionResult UpdateTeacher(teacher teacher)
        {
            if (ModelState.IsValid)
            {
                var res = _context.TEACHERs.FirstOrDefault(x => x.teacher_id == teacher.teacher_id);
                res.faculty_id = teacher.faculty_id;
                res.teacher_name = teacher.teacher_name;
                res.birthday = teacher.birthday;
                res.gender = teacher.gender;
                res.address = teacher.address;
                res.phone_number = teacher.phone_number;
                res.email = teacher.email;
                res.image = teacher.image;
                _context.TEACHERs.AddOrUpdate(res);
                _context.SaveChanges();
                TempData["AlertMessage"] = "Cập nhật thông tin giảng viên thành công";
                return RedirectToAction("ManageTeacher");
            }
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            return View(teacher);
        }

        public ActionResult DeleteTeacher(string id)
        {
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            var res = _context.TEACHERs.FirstOrDefault(x => x.teacher_id == id);
            return View(res);
        }

        [HttpPost]
        public ActionResult DeleteTeacher(teacher teacher)
        {
            ViewBag.Faculty = new SelectList(_context.FACULTies.ToList(), "faculty_id", "faculty_name");
            var res = _context.TEACHERs.FirstOrDefault(x => x.teacher_id == teacher.teacher_id);
            ViewBag.ErrorTeacher = "";
            var user = _context.Users.FirstOrDefault(x => x.user_name == res.teacher_id);
            _context.Users.Remove(user);
            _context.TEACHERs.Remove(res);
            _context.SaveChanges();
            TempData["AlertMessage"] = "Xóa giảng viên thành công";
            return RedirectToAction("ManageTeacher");
        }

        public ActionResult AddStudent()
        {
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            return View();
        }

        [HttpPost]
        public ActionResult AddStudent(student student)
        {
            if (ModelState.IsValid)
            {
                if (_context.STUDENTs.FirstOrDefault(x => x.student_id == student.student_id) == null)
                {
                    _context.STUDENTs.Add(student);
                    if (_context.Users.FirstOrDefault(x => x.user_name == student.student_id) == null)
                    {
                        var user = new users();
                        user.user_name = student.student_id;
                        user.pass_word = "1";
                        user.role_id = "student";
                        user.status = 1;
                        _context.Users.Add(user);
                    }
                    _context.SaveChanges();
                    ViewBag.ErrorStudent = "";
                    TempData["AlertMessage"] = "Thêm sinh viên thành công";
                    return RedirectToAction("ManageStudent");
                }
                else
                {
                    ViewBag.ErrorStudent = "Mã sinh viên đã tồn tại";
                }
            }
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            return View(student);
        }

        public ActionResult ManageStudent(int? page)
        {
            int pageSize = 5;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listStudent = _context.STUDENTs.ToList();
            return View(listStudent.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult SearchStudent(int? page, string searchStudent)
        {
            int pageSize = 5;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var listStudent = _context.STUDENTs.Where(x => x.student_name.Contains(searchStudent)).ToList();
            ViewBag.SearchStudent = searchStudent;
            return View(listStudent.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult UpdateStudent(string id)
        {
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            var res = _context.STUDENTs.FirstOrDefault(x => x.student_id == id);
            return View(res);
        }

        [HttpPost]
        public ActionResult UpdateStudent(student student)
        {
            if (ModelState.IsValid)
            {
                var res = _context.STUDENTs.FirstOrDefault(x => x.student_id == student.student_id);
                res.classes_id = student.classes_id;
                res.student_name = student.student_name;
                res.birthday = student.birthday;
                res.gender = student.gender;
                res.address = student.address;
                res.phone_number = student.phone_number;
                res.email = student.email;
                res.image = student.image;
                res.year_admission = student.year_admission;
                _context.STUDENTs.AddOrUpdate(res);
                _context.SaveChanges();
                TempData["AlertMessage"] = "Cập nhật thông tin sinh viên thành công";
                return RedirectToAction("ManageStudent");
            }
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            return View(student);
        }

        public ActionResult DeleteStudent(string id)
        {
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            var res = _context.STUDENTs.FirstOrDefault(x => x.student_id == id);
            return View(res);
        }

        [HttpPost]
        public ActionResult DeleteStudent(student student)
        {
            ViewBag.Classes = new SelectList(_context.CLASSes.ToList(), "classes_id", "classes_name");
            var resgisterSubject = _context.REGISTERSUBJECTs.FirstOrDefault(x => x.student_id == student.student_id);
            if (resgisterSubject != null)
            {
                ViewBag.ErrorStudent = "Không thể xóa sinh viên này";
                return View(student);
            }
            else
            {
                var scoreStudent = _context.SCOREs.Where(x => x.student_id == student.student_id);
                if (scoreStudent != null)
                {
                    _context.SCOREs.RemoveRange(scoreStudent);
                }
                var res = _context.STUDENTs.FirstOrDefault(x => x.student_id == student.student_id);
                ViewBag.ErrorStudent = "";
                _context.STUDENTs.Remove(res);
                var user = _context.Users.FirstOrDefault(x => x.user_name == student.student_id);

quan-li-dao-tao/Controllers/FacultyController.cs
using quan_li_dao_tao.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace quan_li_dao_tao.Controllers
{
    public class FacultyController : BaseController
    {
        QLSVDbContext _context = null;

        public FacultyController()
        {
            _context = new QLSVDbContext();
        }
        public ActionResult AddFaculty()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddFaculty(faculty faculty)
        {
            if (ModelState.IsValid)
            {
                if (_context.FACULTies.FirstOrDefault(x => x.faculty_id == faculty.faculty_id) == null)
                {
                    _context.FACULTies.Add(faculty);
                    _context.SaveChanges();
                    ViewBag.ErrorFaculty = "";
                    TempData["AlertMessage"] = "Thêm khoa mới thành công";
                    return RedirectToAction("ManageFaculty");
                }
                else
                {
                    ViewBag.ErrorFaculty = "Mã khoa đã tồn tại";
                }
            }
            return View(faculty);
        }

        public ActionResult ManageFaculty()
        {
            var listFaculty = _context.FACULTies.ToList();
            return View(listFaculty);
        }

        public ActionResult UpdateFaculty(string id)
        {
            var faculty = _context.FACULTies.FirstOrDefault(x => x.faculty_id == id);
            return View(faculty);
        }

        [HttpPost]
        public ActionResult UpdateFaculty(faculty faculty)
        {
            var res = _context.FACULTies.FirstOrDefault(x => x.faculty_id == faculty.faculty_id);
            if (res != null)
            {
                res.faculty_name = faculty.faculty_name;
                _context.FACULTies.AddOrUpdate(res);
                _context.SaveChanges();
            }
            TempData["AlertMessage"] = "Cập nhật thông tin khoa thành công";
            return RedirectToAction("ManageFaculty");
        }

        public ActionResult DeleteFaculty(string id)
        {
            var faculty = _context.FACULTies.FirstOrDefault(x => x.faculty_id == id);
            return View(faculty);
        }

        [HttpPost]
        public ActionResult DeleteFaculty(faculty faculty)
        {
            var teacher = _context.TEACHERs.FirstOrDefault(x => x.faculty_id == faculty.faculty_id);
            var classes = _context.CLASSes.FirstOrDefault(x => x.faculty_id == faculty.faculty_id);
            var res = _context.FACULTies.FirstOrDefault(x => x.faculty_id == faculty.faculty_id);
            if (teacher == null && classes == null)
            {
                _context.FACULTies.Remove(res);
                ViewBag.ErrorFaculty = "";
                _context.SaveChanges();
            }
            else
            {
                ViewBag.ErrorFaculty = "Bạn không thể xóa khoa này";
                return View(faculty);
            }
            TempData["AlertMessage"] = "Xóa khoa thành công";
            return RedirectToAction("ManageFaculty");
        }
    }
}

quan-li-dao-tao/Views/Shared/MenuPartial.cshtml
@{
    quan_li_dao_tao.Models.users user = (quan_li_dao_tao.Models.users)Session["User"];
}

<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: rgba(62,88,113);">
    <!-- Brand Logo -->
    @if (user.role_id == "admin")
    {
        <a href="@Url.Action("Index", "Admin")" class="brand-link animated swing">
            <img src="~/assets/img/logo1.png" alt="DSMS Logo" width="200">
        </a>
    }
    @if (user.role_id == "teacher")
    {
        <a href="@Url.Action("Index", "Teacher")" class="brand-link animated swing">
            <img src="~/assets/img/logo1.png" alt="DSMS Logo" width="200">
        </a>
    }
    @if (user.role_id == "student")
    {
        <a href="@Url.Action("Index", "Student")" class="brand-link animated swing">
            <img src="~/assets/img/logo1.png" alt="DSMS Logo" width="200">
        </a>
    }
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/assets/img/avatar.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">@user.user_name</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        @if (user.role_id == "admin")
        {
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item animated bounceInLeft">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-plane-departure"></i>
                            <p>
                                Faculty
                            </p>
                            <i class="right fas fa-angle-left"></i>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("AddFaculty", "Faculty")" class="nav-link">
                                    <i class="nav-icon fa fa-plus"></i>
                                    <p>Add</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ManageFaculty", "Faculty")" class="nav-link">
                                    <i class="nav-icon fa fa-list"></i>
                                    <p>Manage</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item animated bounceInLeft">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-chalkboard-teacher"></i>
                            <p>
                                Teacher
                            </p>
                            <i class="right fas fa-angle-left"></i>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("AddTeacher", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-plus"></i>
                                    <p>Add</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ManageTeacher", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-list"></i>
                                    <p>Manage</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item animated bounceInLeft">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-people-arrows"></i>
                            <p>
                                Student
                            </p>
                            <i class="right fas fa-angle-left"></i>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("AddStudent", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-plus"></i>
                                    <p>Add</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ManageStudent", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-list"></i>
                                    <p>Manage</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item animated bounceInLeft">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                User
                            </p>
                            <i class="right fas fa-angle-left"></i>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("ManageUser", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-list"></i>
                                    <p>Manage</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item animated bounceInLeft">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                Schedule
                            </p>
                            <i class="right fas fa-angle-left"></i>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("SetupSchedule", "Admin")" class="nav-link">
                                    <i class="nav-icon fa fa-book"></i>
                                    <p>Manage</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        }
        @if (user.role_id == "teacher")
        {
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item">
                        <a href="@Url.Action("Student", "Teacher")" class="nav-link">
                            <i class="nav-icon fa fa-people-arrows"></i>
                            <p>
                                Student
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Score", "Teacher")" class="nav-link">
                            <i class="nav-icon fa fa-paint-brush"></i>
                            <p>
                                Score
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Schedule", "Teacher")" class="nav-link">
                            <i class="nav-icon fa fa-book"></i>
                            <p>
                                Schedule
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("ChangePassword", "Teacher")" class="nav-link">
                            <i class="nav-icon fa fa-user-check"></i>
                            <p>
                                User
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
        }
        @if (user.role_id == "student")
        {
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Student")" class="nav-link">
                            <i class="nav-icon fa fa-user"></i>
                            <p>
                                My Profile
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Score", "Student")" class="nav-link">
                            <i class="nav-icon fa fa-paint-brush"></i>
                            <p>
                                Score
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Register", "Student")" class="nav-link">
                            <i class="nav-icon fa fa-registered"></i>
                            <p>
                                Register
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Schedule", "Student")" class="nav-link">
                            <i class="nav-icon fa fa-book"></i>
                            <p>
                                Schedule
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("ChangePassword", "Student")" class="nav-link">
                            <i class="nav-icon fa fa-user-check"></i>
                            <p>
                                User
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
        }
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

quan-li-dao-tao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bùi Ngọc Tiến - CNPM</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/assets/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/assets/css/adminlte.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Login/Logout">
                        <i class="fas fa-power-off"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        @Html.Partial("MenuPartial")
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/assets/jquery/jquery.min.js"></script>
    <script src="~/assets/js/adminlte.js"></script>
    <script src="~/assets/js/canvasjs.min.js"></script>
    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2", // "light1", "light2", "dark1", "dark2"
                title: {
                    text: "Monthly Sales"
                },
                axisY: {
                    title: "Income"
                },
                data: [{
                    type: "column",
                    showInLegend: true,
                    legendMarkerColor: "grey",
                    legendText: "MMbbl = one million barrels",
                    dataPoints: [
                        { y: 70000, label: "January" },
                        { y: 80000, label: "February" },
                        { y: 90000, label: "March" },
                        { y: 85000, label: "April" },
                        { y: 95000, label: "May" },
                        { y: 100000, label: "June" },
                        { y: 110000, label: "July" },
                        { y: 99000, label: "August" },
                        { y: 120000, label: "September" },
                        { y: 130000, label: "October" },
                        { y: 140000, label: "November" },
                        { y: 145000, label: "December" }
                    ]
                }]
            });
            chart.render();

        }
    </script>
</body>
</html>